# Generated by Django 5.2.3 on 2025-07-20 06:35

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_calendarevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryimages',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='immich_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='immich_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='immich_pat',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='entryimages',
            name='immich_asset_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.user_profile_upload_path),
        ),
    ]
