# Generated by Django 5.2.3 on 2025-07-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_entryimages_image_customuser_immich_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='immich_entry_album_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
