# Generated by Django 5.2.3 on 2025-07-26 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reminder_notified_alter_calendarevent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
